spring:
  application:
    name: TodoApplication

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: root@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
  expiration: 3600000  # JWT token expiration in milliseconds (1 hour)
  refresh-token:
    expiration: 86400000  # Refresh token expiration in milliseconds (1 day)
